FACT-1863 - Send Letter Mock to test Send Letter Client
hmcts/send-letter-mock pull request #11
Opened 2024-08-06 15:26 UTC by RuthKirby

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/FACT-1863

### Change description ###

Adds ability to test the dev environments of Send Letter.

Implementation Decisions

- There is a bean being created more than once that causes conflict so have set Spring property `spring.main.allow-bean-definition-overriding=true` to allow name override
- Few tests, these can be added in future improvements as well as better ways to customise what is sent to Send Letter API

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-08-07 07:49 UTC, joshblackmoor requested changes
Great job. Just a few things :)

2024-08-07 07:49 UTC, joshblackmoor commented on .env
> +SEND_LETTER_URL=xxxxxxxx
can we remove the actual env file and put it in the gitignore, just prevents someone accidentally pushing up secrets

2024-08-07 07:49 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/client/controllers/MockSendController.java
> +        File file = new File(Objects.requireNonNull(classLoader.getResource("test_pdf.pdf")).getFile());
Think you will need to upload that PDF to the repo for this to work

2024-08-07 07:49 UTC, joshblackmoor commented on build.gradle
> +  annotationProcessor 'org.projectlombok:lombok'
Lombok can go in the plugins section and be removed from here. e.g. 

plugins {
   id 'io.freefair.lombok' version '8.6'
}

2024-08-07 07:49 UTC, joshblackmoor commented on src/main/resources/application.yaml
> +  url: ${SEND_LETTER_URL}
if we add defaults for these, it may allow the build to run in github e.g. 
SEND_LETTER_URL:https://localhost:1234

2024-08-07 07:49 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/client/controllers/MockSendController.java
> +@Validated
nothing validated can be removed

2024-08-07 07:49 UTC, joshblackmoor commented on README.md
> +class e.g. you could change the additional data sent in the request to Send Letter.There should also be two test PDFs in
PDFs need to be committed as can't see them in resources folder

2024-08-09 10:03 UTC, joshblackmoor approved these changes

2024-08-09 10:03 UTC, amstevenson approved these changes

2024-08-09 10:03 UTC, merged